# Generated by Django 2.2.8 on 2020-03-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Deportes', 'Deportes'), ('Tecnología', 'Tecnología'), ('Arte', 'Arte'), ('Educación', 'Educación')], max_length=10)),
                ('costo', models.CharField(max_length=10)),
                ('tipo', models.BooleanField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('CI', models.IntegerField()),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CI', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('voter', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codices.Question')),
            ],
        ),
    ]
